% This program first trains the DNN using training data, then tests the DNN using test data, 
% and compares the resulting classification with the test labels to calculate the classification accuracy.
% Input: TrainData.mat, TrainLabel.mat, TestData.mat, TestLabel.mat
% Output: Table.mat, stdTable.mat
clear;
clc;
close all;
load TrainData.mat;
load TrainLabel.mat;
load TestData.mat;
load TestLabel.mat;

TrainData=abs(TrainData);
TestData=abs(TestData);


fftsize=1024;
chipSeqLen=1280;

% train neural network
fc_layer = [
    featureInputLayer(fftsize, "Name", "input")

    fullyConnectedLayer(1024, "Name", "fc-1")

    fullyConnectedLayer(2048, "Name", "fc-2")

    fullyConnectedLayer(4096, "Name", "fc-3")

    softmaxLayer("Name", "softmax")
    classificationLayer("Name", "classification")
    ];

miniBatchSize = ceil(size(TrainData,1)/100);

options = trainingOptions('adam', ...
    'ExecutionEnvironment','gpu', ...
    'MaxEpochs',10, ...
    'MiniBatchSize',miniBatchSize, ...
    'ValidationData',{TestData,TestLabel}, ...
    'GradientThreshold',Inf, ...
    'Shuffle','every-epoch', ...
    'Verbose',false, ...
    'Plots','training-progress');

net = trainNetwork(TrainData, TrainLabel, fc_layer, options);
save('myNet.mat', 'net');

% use trained neural network to conduct classification.
load('myNet.mat', 'net');
[YPred prob] = classify(net, TestData, 'MiniBatchSize', miniBatchSize);

PredLabel=single(YPred(1:chipSeqLen*10,1));


figure;
plot(PredLabel,'b+');hold on;
plot(single(TestLabel(1:length(PredLabel))),'ro');hold on;
ylabel('label');
xlabel('received chips');
legend('predicted label','actual label');

save PredLabel.mat PredLabel;


% The classification results generated by the above program refer to the classification of combined chips.
% We need to use the following program to transform combined chips into four separate chip sequences emitted by four victim computers.
% The test labels are also refers to combined chips, they also need to be
% transform into four separate chip sequences.
load PredLabel.mat;
stdLabel=single(TestLabel(1:chipSeqLen*10)');
Table=zeros(length(PredLabel),4);
stdTable=zeros(length(PredLabel),4);
for row=1:1:length(PredLabel)
    A=ceil(stdLabel(row)/8^3);
    B=ceil((stdLabel(row)-(A-1)*8^3)/8^2);
    C=ceil((stdLabel(row)-(A-1)*8^3-(B-1)*8^2)/8);
    D=ceil(stdLabel(row)-(A-1)*8^3-(B-1)*8^2-(C-1)*8);
    a=ceil(PredLabel(row)/8^3);
    b=ceil((PredLabel(row)-(a-1)*8^3)/8^2);
    c=ceil((PredLabel(row)-(a-1)*8^3-(b-1)*8^2)/8);
    d=ceil(PredLabel(row)-(a-1)*8^3-(b-1)*8^2-(c-1)*8);
    stdTable(row,:)=[A,B,C,D];
    Table(row,:)=[a,b,c,d];
end

% Then, we calculate the chip accuracy for each of the four separate chip sequences.
mean(Table(:,1) == stdTable(:,1))
mean(Table(:,2) == stdTable(:,2))
mean(Table(:,3) == stdTable(:,3))
mean(Table(:,4) == stdTable(:,4))

% We save the four separate chip sequences in a table for further calculating symbol error
% rate
save Table.mat Table; % results generated by neural networks
save stdTable.mat stdTable;% Correct chip sequence derived from test labels
